name: yeshelpinghand
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_screenutil: ^5.5.3+2

  #A Flutter widget rendering static HTML and CSS as Flutter widgets.
  # flutter_html: ^2.2.1

  dio: ^5.3.3

  #Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
  hive: ^2.2.3

  #Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.0.11

  hive_flutter: ^1.1.0

  get: ^4.6.5

  fluttertoast: ^8.0.9

  # open_mail_app: ^0.4.5

  carousel_slider: ^4.1.1

  # A Flutter plugin that provides a Google Maps widget.
  # google_maps_flutter: ^2.2.1

  cached_network_image:

  #A list with helper methods to programmatically scroll to an item.
  # scrollable_positioned_list: ^0.3.5

  #Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  flutter_secure_storage: ^8.1.0

  #A pure Dart library that checks for internet by opening a socket to a list of specified addresses, each with individual port and timeout. Defaults are provided for convenience.
  internet_connection_checker: ^1.0.0+1

  #Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.1.1

  #Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
  lottie: ^2.6.0

  #Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.18.0

  #Approximate how your Flutter app looks and performs on another device.
  device_preview: ^1.1.0

  #A flutter implementation of React hooks. It adds a new kind of widget with enhanced code reuse.
  flutter_hooks: ^0.20.3

  #An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^0.23.0

  #Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
  # flutter_staggered_grid_view: ^0.7.0

  #A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  #A Dart mock library which simplifies mocking with null safety support and no manual mocks or code generation.
  mocktail: ^1.0.1

  #A mock framework inspired by Mockito with APIs for Fakes, Mocks, behavior verification, and stubbing.
  mockito: ^5.3.2

  #A Flutter implementation of an expandable and animated floating search bar, also known as persistent search.
  material_floating_search_bar_2: ^0.5.0

  #A simple yet fully customizable ratingbar for flutter which also include a rating bar indicator, supporting any fraction of rating.
  flutter_rating_bar: ^4.0.1

  # for refreshing the list in showmore
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons:

  #A collection of loading indicators animated with flutter. Heavily inspired by @tobiasahlin's SpinKit.
  flutter_spinkit: ^5.1.0
  #Flutter plugin for Google Sign-In, a secure authentication system for signing in with a Google account on Android and iOS.
  # google_sign_in: ^6.0.2

  #Flutter plugin for Firebase Auth, enabling Android and iOS authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter.
  # firebase_auth: ^4.0.0

  #The easiest way to add facebook login to your flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web and macOS.
  # flutter_facebook_auth: ^4.1.0

  font_awesome_flutter: ^10.4.0
  #Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps
  # firebase_core: ^2.8.0

  pinch_zoom_release_unzoom: ^1.0.1

  pinch_zoom: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^3.0.0

  #Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: 2.0.1
  #A build system for Dart code generation and modular compilation.
  build_runner: ^2.2.0

  #A set of high-level APIs over PointyCastle for two-way cryptography.
  encrypt: ^5.0.1

  #Easily configure any flutter application with global variables using a `.env` file.
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.0.0

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anim/
    - assets/svg/
    - assets/gif/
    - assets/.env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        #          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
