name: yeshelpinghand
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_screenutil: ^5.5.3+2

  dio: ^5.3.3

  hive: ^2.2.3

  path_provider: ^2.0.11

  hive_flutter: ^1.1.0

  get: ^4.6.5

  fluttertoast: ^8.0.9

  carousel_slider: ^4.1.1

  cached_network_image:

  flutter_secure_storage: ^8.1.0

  internet_connection_checker: ^1.0.0+1

  pretty_dio_logger: ^1.1.1

  lottie: ^2.6.0

  intl: ^0.18.0

  device_preview: ^1.1.0

  flutter_hooks: ^0.20.3

  flutter_svg: ^0.23.0

  equatable: ^2.0.5

  mocktail: ^1.0.1

  mockito: ^5.3.2

  material_floating_search_bar_2: ^0.5.0

  flutter_rating_bar: ^4.0.1

  pull_to_refresh: ^2.0.0
  flutter_launcher_icons:

  flutter_spinkit: ^5.1.0

  font_awesome_flutter: ^10.4.0

  pinch_zoom_release_unzoom: ^1.0.1

  pinch_zoom: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: 2.0.1

  build_runner: ^2.2.0

  encrypt: ^5.0.1

  flutter_dotenv: ^5.0.2
  url_launcher: ^6.0.0

flutter_icons:
  image_path: "assets/images/app_logo_yhh.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
    - assets/svg/
    - assets/gif/
    - assets/.env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

        - asset: assets/fonts/Roboto-Regular.ttf
